# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from animalai.communicator_objects.items_to_spawn_proto_pb2 import (
    ItemsToSpawn as animalai___communicator_objects___items_to_spawn_proto_pb2___ItemsToSpawn,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


class ArenaConfigurationProto(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    t = ... # type: builtin___int
    blackouts = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]

    @property
    def items(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[animalai___communicator_objects___items_to_spawn_proto_pb2___ItemsToSpawn]: ...

    def __init__(self,
        *,
        t : typing___Optional[builtin___int] = None,
        items : typing___Optional[typing___Iterable[animalai___communicator_objects___items_to_spawn_proto_pb2___ItemsToSpawn]] = None,
        blackouts : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ArenaConfigurationProto: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ArenaConfigurationProto: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"blackouts",b"blackouts",u"items",b"items",u"t",b"t"]) -> None: ...
