# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animalai/communicator_objects/arenas_parameters_proto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from animalai.communicator_objects import arena_parameters_proto_pb2 as animalai_dot_communicator__objects_dot_arena__parameters__proto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='animalai/communicator_objects/arenas_parameters_proto.proto',
  package='communicator_objects',
  syntax='proto3',
  serialized_pb=_b('\n;animalai/communicator_objects/arenas_parameters_proto.proto\x12\x14\x63ommunicator_objects\x1a:animalai/communicator_objects/arena_parameters_proto.proto\"\xc9\x01\n\x15\x41renasParametersProto\x12G\n\x06\x61renas\x18\x01 \x03(\x0b\x32\x37.communicator_objects.ArenasParametersProto.ArenasEntry\x12\x0c\n\x04seed\x18\x02 \x01(\x05\x1aY\n\x0b\x41renasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x39\n\x05value\x18\x02 \x01(\x0b\x32*.communicator_objects.ArenaParametersProto:\x02\x38\x01\x42\x14\xaa\x02\x11\x41\x41IOCommunicatorsb\x06proto3')
  ,
  dependencies=[animalai_dot_communicator__objects_dot_arena__parameters__proto__pb2.DESCRIPTOR,])




_ARENASPARAMETERSPROTO_ARENASENTRY = _descriptor.Descriptor(
  name='ArenasEntry',
  full_name='communicator_objects.ArenasParametersProto.ArenasEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='communicator_objects.ArenasParametersProto.ArenasEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='communicator_objects.ArenasParametersProto.ArenasEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=347,
)

_ARENASPARAMETERSPROTO = _descriptor.Descriptor(
  name='ArenasParametersProto',
  full_name='communicator_objects.ArenasParametersProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arenas', full_name='communicator_objects.ArenasParametersProto.arenas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seed', full_name='communicator_objects.ArenasParametersProto.seed', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ARENASPARAMETERSPROTO_ARENASENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=347,
)

_ARENASPARAMETERSPROTO_ARENASENTRY.fields_by_name['value'].message_type = animalai_dot_communicator__objects_dot_arena__parameters__proto__pb2._ARENAPARAMETERSPROTO
_ARENASPARAMETERSPROTO_ARENASENTRY.containing_type = _ARENASPARAMETERSPROTO
_ARENASPARAMETERSPROTO.fields_by_name['arenas'].message_type = _ARENASPARAMETERSPROTO_ARENASENTRY
DESCRIPTOR.message_types_by_name['ArenasParametersProto'] = _ARENASPARAMETERSPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArenasParametersProto = _reflection.GeneratedProtocolMessageType('ArenasParametersProto', (_message.Message,), dict(

  ArenasEntry = _reflection.GeneratedProtocolMessageType('ArenasEntry', (_message.Message,), dict(
    DESCRIPTOR = _ARENASPARAMETERSPROTO_ARENASENTRY,
    __module__ = 'animalai.communicator_objects.arenas_parameters_proto_pb2'
    # @@protoc_insertion_point(class_scope:communicator_objects.ArenasParametersProto.ArenasEntry)
    ))
  ,
  DESCRIPTOR = _ARENASPARAMETERSPROTO,
  __module__ = 'animalai.communicator_objects.arenas_parameters_proto_pb2'
  # @@protoc_insertion_point(class_scope:communicator_objects.ArenasParametersProto)
  ))
_sym_db.RegisterMessage(ArenasParametersProto)
_sym_db.RegisterMessage(ArenasParametersProto.ArenasEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\021AAIOCommunicators'))
_ARENASPARAMETERSPROTO_ARENASENTRY.has_options = True
_ARENASPARAMETERSPROTO_ARENASENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
